name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Clone CCExtraDialogue
        uses: actions/checkout@v2
      - name: Clone cc-eventscript-parser
        uses: actions/checkout@v2
        with:
          repository: EL20202/cc-eventscript-parser
          token: ${{ secrets.PAT }}
          path: parser

      - name: Install dependencies
        run: sudo apt update; sudo apt install zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10-dev'

      - name: Compile CCES files
        run: python3.10 parser/cc_eventscript_parser.py src/dialogues/*

      - name: Create archives
        run: |
          zip -q cc_extra_dialogue.ccmod assets patches plugin.js ccmod.json package.json icon.png
          tar -czf cc_extra_dialogue.tar.gz --transform 's,^,cc_extra_dialogue/,' assets patches plugin.js ccmod.json package.json icon.png

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'dev'
          prerelease: true
          title: 'CCES Dev'
          files: |
            cc_extra_dialogue.ccmod
            cc_extra_dialogue.tar.gz
