name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Clone CCExtraDialogue
        uses: actions/checkout@v2
      - name: Clone cc-eventscript-parser
        uses: actions/checkout@v2
        with:
          repository: EL20202/cc-eventscript-parser
          token: ${{ secrets.PAT }}
          path: parser

      - name: Install dependencies
        run: sudo apt update; sudo apt install zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10-dev'

      - name: Compile CCES files
        run: python3.10 parser/cc_eventscript_parser.py -r src/dialogues/

      - name: Create CCED archives
        run: |
          zip -q -r cc_extra_dialogue.ccmod assets patches js prestart.js ccmod.json package.json icon.png
          tar -czf cc_extra_dialogue.tar.gz --transform 's,^,cc_extra_dialogue/,' assets patches js prestart.js ccmod.json package.json icon.png

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} -d -t "CCED ${{ steps.get_version.outputs.VERSION }}" -n "$(cat .github/workflows/release_body_template.md)" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: cc_extra_dialogue.ccmod cc_extra_dialogue.tar.gz
